services:
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./interface:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  bucket1:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=Crime DataSet
      - BUCKET_URL=http://bucket1:5000
      - BUCKET_FOLDER=/app/buckets/bucket1
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket2:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=Medical DataSet (Consultations)
      - BUCKET_URL=http://bucket2:5000
      - BUCKET_FOLDER=/app/buckets/bucket2
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket3:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=BBC News DataSet
      - BUCKET_URL=http://bucket3:5000
      - BUCKET_FOLDER=/app/buckets/bucket3
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

networks:
  app-network:
    driver: bridge