services:
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./interface:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  bucket1:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=bucket1
      - BUCKET_URL=http://bucket1:5000
      - BUCKET_FOLDER=/app/buckets/bucket1
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket2:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=bucket2
      - BUCKET_URL=http://bucket2:5000
      - BUCKET_FOLDER=/app/buckets/bucket2
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket3:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=bucket3
      - BUCKET_URL=http://bucket3:5000
      - BUCKET_FOLDER=/app/buckets/bucket3
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket4:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=bucket4
      - BUCKET_URL=http://bucket4:5000
      - BUCKET_FOLDER=/app/buckets/bucket4
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

  bucket5:
    build:
      context: ./bucket
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./bucket:/app
      - ./bucket/buckets:/app/buckets
    environment:
      - FLASK_ENV=development
      - BUCKET_NAME=bucket5
      - BUCKET_URL=http://bucket5:5000
      - BUCKET_FOLDER=/app/buckets/bucket5
      - OLLAMA_HOST=http://host.docker.internal:11434
    networks:
      - app-network

networks:
  app-network:
    driver: bridge