FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Node/ Node/
COPY InterfaceWebService.py .
COPY main_interface.py .
COPY templates/ templates/

CMD ["python", "main_interface.py"]