FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY BucketWebService.py .
COPY main_bucket.py .
COPY DAO/ DAO/
COPY Docs/ Docs/
COPY Embeddings/ Embeddings/
COPY Manager/ Manager/
COPY Controller/ Controller/

CMD ["python", "main_bucket.py"]